// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: oberon.flex

import java.io.*;
import exceptions.*;
import java_cup.runtime.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class OberonScanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1100\1\u1d00"+
    "\1\u1e00\1\u1f00\12\u2000\1\u2100\1\u2200\1\u2300\1\u2000\1\u2400"+
    "\1\u2500\2\u2000\31\u1100\1\u2600\121\u1100\1\u2700\4\u1100\1\u2800"+
    "\1\u1100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\1\u2e00\53\u1100"+
    "\1\u2f00\10\u3000\31\u2000\1\u1100\1\u3100\1\u3200\1\u1100\1\u3300"+
    "\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u3a00\3\u2000"+
    "\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\3\u2000\1\u4000\1\u4100"+
    "\4\u2000\1\u4200\11\u2000\3\u1100\1\u4300\1\u4400\13\u2000\4\u1100"+
    "\1\u4500\63\u2000\2\u1100\1\u4600\4\u2000\1\u4700\100\u2000\1\u4800"+
    "\40\u2000\1\u4900\1\u4a00\1\u2000\1\u4b00\1\u4c00\1\u4d00\1\u4e00"+
    "\26\u2000\1\u4f00\21\u2000\246\u1100\1\u5000\20\u1100\1\u5100\1\u5200"+
    "\77\u2000\2\u1100\1\u5200\u0b05\u2000\1\u5300\1\u5400\u02fe\u2000";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\16\0\4\3"+
    "\1\1\2\3\1\5\1\6\1\3\1\7\1\3\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\3\1\17"+
    "\7\20\2\21\1\22\1\23\1\24\1\25\1\26\2\3"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\2\6\1\40\1\41\1\42\1\43\1\44\1\6"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\6\1\53"+
    "\1\6\1\54\1\3\1\55\1\3\1\6\1\3\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\2\6\1\40\1\41\1\42\1\43\1\44\1\6\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\6\1\53\1\6"+
    "\1\3\1\56\1\3\1\57\41\0\2\3\4\6\4\3"+
    "\1\6\2\3\1\0\7\3\1\6\4\3\1\6\5\3"+
    "\27\6\1\3\37\6\1\3\70\6\2\37\115\6\1\46"+
    "\u0142\6\4\3\14\6\16\3\5\6\7\3\1\6\1\3"+
    "\1\6\21\3\160\0\5\6\1\3\2\6\2\3\4\6"+
    "\10\3\1\6\1\3\3\6\1\3\1\6\1\3\24\6"+
    "\1\3\123\6\1\3\213\6\1\3\5\0\2\3\236\6"+
    "\11\3\46\6\2\3\1\6\7\3\47\6\7\3\1\6"+
    "\1\3\55\0\1\3\1\0\1\3\2\0\1\3\2\0"+
    "\1\3\1\0\10\3\33\6\5\3\3\6\15\3\5\0"+
    "\6\3\1\6\4\3\13\0\5\3\53\6\37\0\4\3"+
    "\2\6\1\0\143\6\1\3\1\6\10\0\1\3\6\0"+
    "\2\6\2\0\1\3\4\0\2\6\12\0\3\6\2\3"+
    "\1\6\17\3\1\0\1\6\1\0\36\6\33\0\2\3"+
    "\131\6\13\0\1\6\16\3\12\0\41\6\11\0\2\6"+
    "\4\3\1\6\5\3\26\6\4\0\1\6\11\0\1\6"+
    "\3\0\1\6\5\0\22\3\31\6\3\0\104\3\1\6"+
    "\1\3\13\6\67\3\33\0\1\3\4\0\66\6\3\0"+
    "\1\6\22\0\1\6\7\0\12\6\2\0\2\3\12\0"+
    "\1\3\7\6\1\3\7\6\1\3\3\0\1\3\10\6"+
    "\2\3\2\6\2\3\26\6\1\3\7\6\1\3\1\6"+
    "\3\3\4\6\2\3\1\0\1\6\7\0\2\3\2\0"+
    "\2\3\3\0\1\6\10\3\1\0\4\3\2\6\1\3"+
    "\3\6\2\0\2\3\12\0\4\6\7\3\1\6\5\3"+
    "\3\0\1\3\6\6\4\3\2\6\2\3\26\6\1\3"+
    "\7\6\1\3\2\6\1\3\2\6\1\3\2\6\2\3"+
    "\1\0\1\3\5\0\4\3\2\0\2\3\3\0\3\3"+
    "\1\0\7\3\4\6\1\3\1\6\7\3\14\0\3\6"+
    "\1\0\13\3\3\0\1\3\11\6\1\3\3\6\1\3"+
    "\26\6\1\3\7\6\1\3\2\6\1\3\5\6\2\3"+
    "\1\0\1\6\10\0\1\3\3\0\1\3\3\0\2\3"+
    "\1\6\17\3\2\6\2\0\2\3\12\0\1\3\1\6"+
    "\17\3\3\0\1\3\10\6\2\3\2\6\2\3\26\6"+
    "\1\3\7\6\1\3\2\6\1\3\5\6\2\3\1\0"+
    "\1\6\7\0\2\3\2\0\2\3\3\0\10\3\2\0"+
    "\4\3\2\6\1\3\3\6\2\0\2\3\12\0\1\3"+
    "\1\6\20\3\1\0\1\6\1\3\6\6\3\3\3\6"+
    "\1\3\4\6\3\3\2\6\1\3\1\6\1\3\2\6"+
    "\3\3\2\6\3\3\3\6\3\3\14\6\4\3\5\0"+
    "\3\3\3\0\1\3\4\0\2\3\1\6\6\3\1\0"+
    "\16\3\12\0\11\3\1\6\7\3\3\0\1\3\10\6"+
    "\1\3\3\6\1\3\27\6\1\3\12\6\1\3\5\6"+
    "\3\3\1\6\7\0\1\3\3\0\1\3\4\0\7\3"+
    "\2\0\1\3\2\6\6\3\2\6\2\0\2\3\12\0"+
    "\22\3\2\0\1\3\10\6\1\3\3\6\1\3\27\6"+
    "\1\3\12\6\1\3\5\6\2\3\1\0\1\6\7\0"+
    "\1\3\3\0\1\3\4\0\7\3\2\0\7\3\1\6"+
    "\1\3\2\6\2\0\2\3\12\0\1\3\2\6\17\3"+
    "\2\0\1\3\10\6\1\3\3\6\1\3\51\6\2\3"+
    "\1\6\7\0\1\3\3\0\1\3\4\0\1\6\10\3"+
    "\1\0\10\3\2\6\2\0\2\3\12\0\12\3\6\6"+
    "\2\3\2\0\1\3\22\6\3\3\30\6\1\3\11\6"+
    "\1\3\1\6\2\3\7\6\3\3\1\0\4\3\6\0"+
    "\1\3\1\0\1\3\10\0\22\3\2\0\15\3\60\6"+
    "\1\0\2\6\7\0\4\3\10\6\10\0\1\3\12\0"+
    "\47\3\2\6\1\3\1\6\2\3\2\6\1\3\1\6"+
    "\2\3\1\6\6\3\4\6\1\3\7\6\1\3\3\6"+
    "\1\3\1\6\1\3\1\6\2\3\2\6\1\3\4\6"+
    "\1\0\2\6\6\0\1\3\2\0\1\6\2\3\5\6"+
    "\1\3\1\6\1\3\6\0\2\3\12\0\2\3\4\6"+
    "\40\3\1\6\27\3\2\0\6\3\12\0\13\3\1\0"+
    "\1\3\1\0\1\3\1\0\4\3\2\0\10\6\1\3"+
    "\44\6\4\3\24\0\1\3\2\0\5\6\13\0\1\3"+
    "\44\0\11\3\1\0\71\3\53\6\24\0\1\6\12\0"+
    "\6\3\6\6\4\0\4\6\3\0\1\6\3\0\2\6"+
    "\7\0\3\6\4\0\15\6\14\0\1\6\17\0\2\3"+
    "\46\6\1\3\1\6\5\3\1\6\2\3\53\6\1\3"+
    "\u014d\6\1\3\4\6\2\3\7\6\1\3\1\6\1\3"+
    "\4\6\2\3\51\6\1\3\4\6\2\3\41\6\1\3"+
    "\4\6\2\3\7\6\1\3\1\6\1\3\4\6\2\3"+
    "\17\6\1\3\71\6\1\3\4\6\2\3\103\6\2\3"+
    "\3\0\40\3\20\6\20\3\125\6\14\3\u016c\6\2\3"+
    "\21\6\1\3\32\6\5\3\113\6\3\3\3\6\17\3"+
    "\15\6\1\3\4\6\3\0\13\3\22\6\3\0\13\3"+
    "\22\6\2\0\14\3\15\6\1\3\3\6\1\3\2\0"+
    "\14\3\64\6\40\0\3\3\1\6\3\3\2\6\1\0"+
    "\2\3\12\0\41\3\3\0\2\3\12\0\6\3\130\6"+
    "\10\3\51\6\1\0\1\6\5\3\106\6\12\3\35\6"+
    "\3\3\14\0\4\3\14\0\12\3\12\0\36\6\2\3"+
    "\5\6\13\3\54\6\4\3\21\0\7\6\2\0\6\3"+
    "\12\0\46\3\27\6\5\0\4\3\65\6\12\0\1\3"+
    "\35\0\2\3\13\0\6\3\12\0\15\3\1\6\130\3"+
    "\5\0\57\6\21\0\7\6\4\3\12\0\21\3\11\0"+
    "\14\3\3\0\36\6\15\0\2\6\12\0\54\6\16\0"+
    "\14\3\44\6\24\0\10\3\12\0\3\3\3\6\12\0"+
    "\44\6\122\3\3\0\1\3\25\0\4\6\1\0\4\6"+
    "\3\0\2\6\11\3\300\6\47\0\25\3\4\0\26\6"+
    "\2\3\6\6\2\3\46\6\2\3\6\6\2\3\10\6"+
    "\1\3\1\6\1\3\1\6\1\3\1\6\1\3\37\6"+
    "\2\3\65\6\1\3\7\6\1\3\1\6\3\3\3\6"+
    "\1\3\7\6\3\3\4\6\2\3\6\6\4\3\15\6"+
    "\5\3\3\6\1\3\7\6\16\3\5\0\32\3\5\0"+
    "\20\3\2\6\23\3\1\6\13\3\5\0\5\3\6\0"+
    "\1\3\1\6\15\3\1\6\20\3\15\6\3\3\33\6"+
    "\25\3\15\0\4\3\1\0\3\3\14\0\21\3\1\6"+
    "\4\3\1\6\2\3\12\6\1\3\1\6\3\3\5\6"+
    "\6\3\1\6\1\3\1\6\1\3\1\6\1\3\4\6"+
    "\1\3\13\6\2\3\4\6\5\3\5\6\4\3\1\6"+
    "\21\3\51\6\u0177\3\57\6\1\3\57\6\1\3\205\6"+
    "\6\3\4\6\3\0\2\6\14\3\46\6\1\3\1\6"+
    "\5\3\1\6\2\3\70\6\7\3\1\6\17\3\1\0"+
    "\27\6\11\3\7\6\1\3\7\6\1\3\7\6\1\3"+
    "\7\6\1\3\7\6\1\3\7\6\1\3\7\6\1\3"+
    "\7\6\1\3\40\0\57\3\1\6\325\3\3\6\31\3"+
    "\11\6\6\0\1\3\5\6\2\3\5\6\4\3\126\6"+
    "\2\3\2\0\2\3\3\6\1\3\132\6\1\3\4\6"+
    "\5\3\51\6\3\3\136\6\21\3\33\6\65\3\306\6"+
    "\112\3\315\6\63\3\215\6\103\3\56\6\2\3\15\6"+
    "\3\3\20\6\12\0\2\6\24\3\57\6\1\0\4\3"+
    "\12\0\1\3\31\6\7\3\1\0\120\6\2\0\45\3"+
    "\11\6\2\3\147\6\2\3\4\6\1\3\4\6\14\3"+
    "\13\6\115\3\12\6\1\0\3\6\1\0\4\6\1\0"+
    "\27\6\5\0\20\3\1\6\7\3\64\6\14\3\2\0"+
    "\62\6\21\0\13\3\12\0\6\3\22\0\6\6\3\3"+
    "\1\6\4\3\12\0\34\6\10\0\2\3\27\6\15\0"+
    "\14\3\35\6\3\3\4\0\57\6\16\0\16\3\1\6"+
    "\12\0\46\3\51\6\16\0\11\3\3\6\1\0\10\6"+
    "\2\0\2\3\12\0\6\3\27\6\3\3\1\6\1\0"+
    "\4\3\60\6\1\0\1\6\3\0\2\6\2\0\5\6"+
    "\2\0\1\6\1\0\1\6\30\3\3\6\2\3\13\6"+
    "\5\0\2\3\3\6\2\0\12\3\6\6\2\3\6\6"+
    "\2\3\6\6\11\3\7\6\1\3\7\6\221\3\43\6"+
    "\10\0\1\3\2\0\2\3\12\0\6\3\244\6\14\3"+
    "\27\6\4\3\61\6\u0104\3\156\6\2\3\152\6\46\3"+
    "\7\6\14\3\5\6\5\3\1\6\1\0\12\6\1\3"+
    "\15\6\1\3\5\6\1\3\1\6\1\3\2\6\1\3"+
    "\2\6\1\3\154\6\41\3\153\6\22\3\100\6\2\3"+
    "\66\6\50\3\15\6\3\3\20\0\20\3\7\0\14\3"+
    "\2\6\30\3\3\6\31\3\1\6\6\3\5\6\1\3"+
    "\207\6\2\3\1\0\4\3\1\6\13\3\12\0\7\3"+
    "\32\6\4\3\1\6\1\3\32\6\13\3\131\6\3\3"+
    "\6\6\2\3\6\6\2\3\6\6\2\3\3\6\3\3"+
    "\2\6\3\3\2\6\22\3\3\0\4\3\14\6\1\3"+
    "\32\6\1\3\23\6\1\3\2\6\1\3\17\6\2\3"+
    "\16\6\42\3\173\6\105\3\65\6\210\3\1\0\202\3"+
    "\35\6\3\3\61\6\57\3\37\6\21\3\33\6\65\3"+
    "\36\6\2\3\44\6\4\3\10\6\1\3\5\6\52\3"+
    "\236\6\2\3\12\0\126\3\6\6\2\3\1\6\1\3"+
    "\54\6\1\3\2\6\3\3\1\6\2\3\27\6\252\3"+
    "\26\6\12\3\32\6\106\3\70\6\6\3\2\6\100\3"+
    "\1\6\3\0\1\3\2\0\5\3\4\0\4\6\1\3"+
    "\3\6\1\3\33\6\4\3\3\0\4\3\1\0\40\3"+
    "\35\6\203\3\66\6\12\3\26\6\12\3\23\6\215\3"+
    "\111\6\267\3\3\0\65\6\17\0\37\3\12\0\20\3"+
    "\3\0\55\6\13\0\2\3\1\0\22\3\31\6\7\3"+
    "\12\0\6\3\3\0\44\6\16\0\1\3\12\0\100\3"+
    "\3\0\60\6\16\0\4\6\13\3\12\0\246\3\53\6"+
    "\15\0\10\3\12\0\66\3\157\6\221\3\143\6\235\3"+
    "\57\6\321\3\71\6\307\3\105\6\13\3\1\6\56\0"+
    "\20\3\4\0\15\6\140\3\2\6\u0163\3\5\0\3\3"+
    "\26\0\2\3\7\0\36\3\4\0\224\3\3\0\273\3"+
    "\125\6\1\3\107\6\1\3\2\6\2\3\1\6\2\3"+
    "\2\6\2\3\4\6\1\3\14\6\1\3\1\6\1\3"+
    "\7\6\1\3\101\6\1\3\4\6\2\3\10\6\1\3"+
    "\7\6\1\3\34\6\1\3\4\6\1\3\5\6\1\3"+
    "\1\6\3\3\7\6\1\3\u0154\6\2\3\31\6\1\3"+
    "\31\6\1\3\37\6\1\3\31\6\1\3\37\6\1\3"+
    "\31\6\1\3\37\6\1\3\31\6\1\3\37\6\1\3"+
    "\31\6\1\3\10\6\2\3\62\0\4\6\1\3\33\6"+
    "\1\3\2\6\1\3\1\6\2\3\1\6\1\3\12\6"+
    "\1\3\4\6\1\3\1\6\1\3\1\6\6\3\1\6"+
    "\4\3\1\6\1\3\1\6\1\3\1\6\1\3\3\6"+
    "\1\3\2\6\1\3\1\6\2\3\1\6\1\3\1\6"+
    "\1\3\1\6\1\3\1\6\1\3\1\6\1\3\2\6"+
    "\1\3\1\6\2\3\4\6\1\3\7\6\1\3\4\6"+
    "\1\3\4\6\1\3\1\6\1\3\12\6\1\3\21\6"+
    "\5\3\3\6\1\3\5\6\1\3\21\6\104\3\327\6"+
    "\51\3\65\6\13\3\336\6\343\3\1\0\36\3\140\0"+
    "\200\3\360\0\20\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[21760];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\2\15\1\16\1\17"+
    "\1\20\1\21\1\22\16\4\1\23\1\24\1\25\4\0"+
    "\2\26\1\27\2\30\1\31\1\32\1\33\5\4\1\34"+
    "\3\4\1\35\2\4\1\36\1\37\10\4\1\0\2\30"+
    "\4\4\1\40\1\4\1\41\2\4\1\42\6\4\1\43"+
    "\2\4\1\2\1\26\4\4\1\44\5\4\1\45\1\4"+
    "\1\46\1\47\1\50\2\4\1\2\1\51\1\52\1\4"+
    "\1\53\1\54\1\55\4\4\1\56\1\57\1\26\1\0"+
    "\2\4\1\60\1\4\1\61\1\4\1\26\1\62\1\63"+
    "\1\4\1\64\1\4\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\60\0\140\0\60\0\220\0\60\0\300"+
    "\0\60\0\360\0\60\0\60\0\60\0\60\0\u0120\0\u0150"+
    "\0\u0180\0\60\0\u01b0\0\60\0\u01e0\0\u0210\0\u0240\0\u0270"+
    "\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0"+
    "\0\u0420\0\u0450\0\u0480\0\60\0\60\0\60\0\60\0\u04b0"+
    "\0\360\0\u04e0\0\u0510\0\60\0\u0540\0\u0570\0\u05a0\0\60"+
    "\0\60\0\60\0\u05d0\0\u0600\0\u0630\0\u0660\0\u0690\0\220"+
    "\0\u06c0\0\u06f0\0\u0720\0\220\0\u0750\0\u0780\0\220\0\220"+
    "\0\u07b0\0\u07e0\0\u0810\0\u0840\0\u0870\0\u08a0\0\u08d0\0\u0900"+
    "\0\u0930\0\u0960\0\u0990\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\220"+
    "\0\u0a80\0\220\0\u0ab0\0\u0ae0\0\u0b10\0\u0b40\0\u0b70\0\u0ba0"+
    "\0\u0bd0\0\u0c00\0\u0c30\0\220\0\u0c60\0\u0c90\0\u0cc0\0\u0cf0"+
    "\0\u0d20\0\u0d50\0\u0d80\0\u0db0\0\220\0\u0de0\0\u0e10\0\u0e40"+
    "\0\u0e70\0\u0ea0\0\220\0\u0ed0\0\220\0\220\0\220\0\u0f00"+
    "\0\u0f30\0\u0f60\0\220\0\220\0\u0f90\0\220\0\220\0\220"+
    "\0\u0fc0\0\u0ff0\0\u1020\0\u1050\0\220\0\u1080\0\u0f60\0\u10b0"+
    "\0\u10e0\0\u1110\0\220\0\u1140\0\220\0\u1170\0\u11a0\0\220"+
    "\0\220\0\u11d0\0\220\0\u1200\0\220";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\2\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\2\6\1\34\1\6\1\35\1\6"+
    "\1\36\1\37\1\40\1\6\1\41\1\6\1\42\1\43"+
    "\1\6\1\44\1\45\1\2\1\46\10\47\1\50\1\47"+
    "\1\51\47\47\1\3\5\47\1\50\1\47\1\51\45\47"+
    "\1\6\5\47\1\6\1\47\1\50\1\47\1\51\4\47"+
    "\3\6\5\47\25\6\14\47\1\52\1\47\1\53\55\47"+
    "\1\50\1\54\1\51\53\47\1\55\1\47\1\50\1\47"+
    "\1\51\4\47\2\17\1\56\5\47\25\55\2\47\1\57"+
    "\7\47\1\55\1\47\1\50\1\47\1\51\4\47\3\20"+
    "\5\47\25\55\14\47\1\50\1\47\1\51\12\47\1\60"+
    "\42\47\1\50\1\47\1\51\12\47\1\61\42\47\1\50"+
    "\1\47\1\51\12\47\1\62\32\47\1\6\5\47\1\6"+
    "\1\47\1\50\1\47\1\51\4\47\3\6\5\47\16\6"+
    "\1\63\6\6\4\47\1\6\5\47\1\6\1\47\1\50"+
    "\1\47\1\51\4\47\3\6\5\47\4\6\1\64\7\6"+
    "\1\65\10\6\4\47\1\6\5\47\1\6\1\47\1\50"+
    "\1\47\1\51\4\47\3\6\5\47\14\6\1\66\10\6"+
    "\4\47\1\6\5\47\1\6\1\47\1\50\1\47\1\51"+
    "\4\47\3\6\5\47\10\6\1\67\3\6\1\70\10\6"+
    "\4\47\1\6\5\47\1\6\1\47\1\50\1\47\1\51"+
    "\4\47\3\6\5\47\11\6\1\71\1\6\1\72\11\6"+
    "\4\47\1\6\5\47\1\6\1\47\1\50\1\47\1\51"+
    "\4\47\3\6\5\47\1\73\24\6\4\47\1\6\5\47"+
    "\1\6\1\47\1\50\1\47\1\51\4\47\3\6\5\47"+
    "\5\6\1\74\5\6\1\75\11\6\4\47\1\6\5\47"+
    "\1\6\1\47\1\50\1\47\1\51\4\47\3\6\5\47"+
    "\14\6\1\76\10\6\4\47\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\5\6\1\77"+
    "\10\6\1\100\6\6\4\47\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\16\6\1\101"+
    "\6\6\4\47\1\6\5\47\1\6\1\47\1\50\1\47"+
    "\1\51\4\47\3\6\5\47\4\6\1\102\20\6\4\47"+
    "\1\6\5\47\1\6\1\47\1\50\1\47\1\51\4\47"+
    "\3\6\5\47\7\6\1\103\6\6\1\104\5\6\1\105"+
    "\4\47\1\6\5\47\1\6\1\47\1\50\1\47\1\51"+
    "\4\47\3\6\5\47\1\106\24\6\4\47\1\6\5\47"+
    "\1\6\1\47\1\50\1\47\1\51\4\47\3\6\5\47"+
    "\7\6\1\107\6\6\1\110\6\6\14\47\1\52\1\47"+
    "\1\0\55\47\1\52\1\47\1\51\45\47\12\53\1\111"+
    "\45\53\1\55\5\47\1\55\1\47\1\50\1\47\1\51"+
    "\4\47\3\55\5\47\25\55\12\47\1\55\1\47\1\50"+
    "\1\47\1\51\4\47\2\112\1\56\5\47\25\55\2\47"+
    "\1\57\11\47\1\50\1\47\1\51\4\47\2\113\1\57"+
    "\34\47\1\57\1\47\1\6\5\47\1\6\1\47\1\50"+
    "\1\47\1\51\4\47\3\6\5\47\16\6\1\114\6\6"+
    "\4\47\1\6\5\47\1\6\1\47\1\50\1\47\1\51"+
    "\4\47\3\6\5\47\6\6\1\115\16\6\4\47\1\6"+
    "\5\47\1\6\1\47\1\50\1\47\1\51\4\47\3\6"+
    "\5\47\14\6\1\116\10\6\4\47\1\6\5\47\1\6"+
    "\1\47\1\50\1\47\1\51\4\47\3\6\5\47\13\6"+
    "\1\117\11\6\4\47\1\6\5\47\1\6\1\47\1\50"+
    "\1\47\1\51\4\47\3\6\5\47\22\6\1\120\2\6"+
    "\4\47\1\6\5\47\1\6\1\47\1\50\1\47\1\51"+
    "\4\47\3\6\5\47\17\6\1\121\5\6\4\47\1\6"+
    "\5\47\1\6\1\47\1\50\1\47\1\51\4\47\3\6"+
    "\5\47\3\6\1\122\21\6\4\47\1\6\5\47\1\6"+
    "\1\47\1\50\1\47\1\51\4\47\3\6\5\47\11\6"+
    "\1\123\13\6\4\47\1\6\5\47\1\6\1\47\1\50"+
    "\1\47\1\51\4\47\3\6\5\47\20\6\1\124\4\6"+
    "\4\47\1\6\5\47\1\6\1\47\1\50\1\47\1\51"+
    "\4\47\3\6\5\47\3\6\1\125\21\6\4\47\1\6"+
    "\5\47\1\6\1\47\1\50\1\47\1\51\4\47\3\6"+
    "\5\47\14\6\1\126\10\6\4\47\1\6\5\47\1\6"+
    "\1\47\1\50\1\47\1\51\4\47\3\6\5\47\1\127"+
    "\1\6\1\130\22\6\4\47\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\4\6\1\131"+
    "\20\6\4\47\1\6\5\47\1\6\1\47\1\50\1\47"+
    "\1\51\4\47\3\6\5\47\21\6\1\132\3\6\4\47"+
    "\1\6\5\47\1\6\1\47\1\50\1\47\1\51\4\47"+
    "\3\6\5\47\15\6\1\133\7\6\4\47\1\6\5\47"+
    "\1\6\1\47\1\50\1\47\1\51\4\47\3\6\5\47"+
    "\16\6\1\134\6\6\4\47\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\10\6\1\135"+
    "\14\6\4\47\1\6\5\47\1\6\1\47\1\50\1\47"+
    "\1\51\4\47\3\6\5\47\10\6\1\136\14\6\4\47"+
    "\11\53\1\137\1\140\45\53\6\47\1\55\1\47\1\50"+
    "\1\47\1\51\4\47\3\112\5\47\25\55\14\47\1\50"+
    "\1\47\1\51\4\47\3\113\36\47\1\6\5\47\1\6"+
    "\1\47\1\50\1\47\1\51\4\47\3\6\5\47\1\141"+
    "\24\6\4\47\1\6\5\47\1\6\1\47\1\50\1\47"+
    "\1\51\4\47\3\6\5\47\10\6\1\142\14\6\4\47"+
    "\1\6\5\47\1\6\1\47\1\50\1\47\1\51\4\47"+
    "\3\6\5\47\11\6\1\143\13\6\4\47\1\6\5\47"+
    "\1\6\1\47\1\50\1\47\1\51\4\47\3\6\5\47"+
    "\17\6\1\144\5\6\4\47\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\4\6\1\145"+
    "\3\6\1\146\14\6\4\47\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\17\6\1\147"+
    "\5\6\4\47\1\6\5\47\1\6\1\47\1\50\1\47"+
    "\1\51\4\47\3\6\5\47\4\6\1\150\20\6\4\47"+
    "\1\6\5\47\1\6\1\47\1\50\1\47\1\51\4\47"+
    "\3\6\5\47\21\6\1\151\3\6\4\47\1\6\5\47"+
    "\1\6\1\47\1\50\1\47\1\51\4\47\3\6\5\47"+
    "\2\6\1\152\22\6\4\47\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\3\6\1\153"+
    "\21\6\4\47\1\6\5\47\1\6\1\47\1\50\1\47"+
    "\1\51\4\47\3\6\5\47\14\6\1\154\10\6\4\47"+
    "\1\6\5\47\1\6\1\47\1\50\1\47\1\51\4\47"+
    "\3\6\5\47\13\6\1\155\11\6\4\47\1\6\5\47"+
    "\1\6\1\47\1\50\1\47\1\51\4\47\3\6\5\47"+
    "\4\6\1\156\20\6\4\47\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\4\6\1\157"+
    "\20\6\4\47\1\6\5\47\1\6\1\47\1\50\1\47"+
    "\1\51\4\47\3\6\5\47\11\6\1\160\13\6\4\47"+
    "\1\6\5\47\1\6\1\47\1\50\1\47\1\51\4\47"+
    "\3\6\5\47\20\6\1\161\4\6\4\47\60\0\11\53"+
    "\1\162\1\140\45\53\1\6\5\47\1\6\1\47\1\50"+
    "\1\47\1\51\4\47\3\6\5\47\24\6\1\163\4\47"+
    "\1\6\5\47\1\6\1\47\1\50\1\47\1\51\4\47"+
    "\3\6\5\47\13\6\1\164\11\6\4\47\1\6\5\47"+
    "\1\6\1\47\1\50\1\47\1\51\4\47\3\6\5\47"+
    "\4\6\1\165\20\6\4\47\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\20\6\1\166"+
    "\4\6\4\47\1\6\5\47\1\6\1\47\1\50\1\47"+
    "\1\51\4\47\3\6\5\47\5\6\1\167\17\6\4\47"+
    "\1\6\5\47\1\6\1\47\1\50\1\47\1\51\4\47"+
    "\3\6\5\47\4\6\1\170\20\6\4\47\1\6\5\47"+
    "\1\6\1\47\1\50\1\47\1\51\4\47\3\6\5\47"+
    "\6\6\1\171\16\6\4\47\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\11\6\1\172"+
    "\13\6\4\47\1\6\5\47\1\6\1\47\1\50\1\47"+
    "\1\51\4\47\3\6\5\47\4\6\1\173\20\6\4\47"+
    "\1\6\5\47\1\6\1\47\1\50\1\47\1\51\4\47"+
    "\3\6\5\47\16\6\1\174\6\6\4\47\1\6\5\47"+
    "\1\6\1\47\1\50\1\47\1\51\4\47\3\6\5\47"+
    "\4\6\1\175\20\6\4\47\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\4\6\1\176"+
    "\20\6\4\47\12\177\1\200\45\177\1\6\5\47\1\6"+
    "\1\47\1\50\1\47\1\51\4\47\3\6\5\47\1\201"+
    "\24\6\4\47\1\6\5\47\1\6\1\47\1\50\1\47"+
    "\1\51\4\47\3\6\5\47\4\6\1\202\20\6\4\47"+
    "\1\6\5\47\1\6\1\47\1\50\1\47\1\51\4\47"+
    "\3\6\5\47\4\6\1\203\20\6\4\47\1\6\5\47"+
    "\1\6\1\47\1\50\1\47\1\51\4\47\3\6\5\47"+
    "\3\6\1\204\21\6\4\47\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\3\6\1\205"+
    "\21\6\4\47\1\6\5\47\1\6\1\47\1\50\1\47"+
    "\1\51\4\47\3\6\5\47\11\6\1\206\13\6\4\47"+
    "\11\177\1\0\1\207\45\177\1\6\5\47\1\6\1\47"+
    "\1\50\1\47\1\51\4\47\3\6\5\47\13\6\1\210"+
    "\11\6\4\47\1\6\5\47\1\6\1\47\1\50\1\47"+
    "\1\51\4\47\3\6\5\47\16\6\1\211\6\6\4\47"+
    "\1\6\5\47\1\6\1\47\1\50\1\47\1\51\4\47"+
    "\3\6\5\47\21\6\1\212\3\6\4\47\1\6\5\47"+
    "\1\6\1\47\1\50\1\47\1\51\4\47\3\6\5\47"+
    "\13\6\1\213\11\6\4\47\12\177\1\207\45\177\1\6"+
    "\5\47\1\6\1\47\1\50\1\47\1\51\4\47\3\6"+
    "\5\47\16\6\1\214\6\6\4\47\1\6\5\47\1\6"+
    "\1\47\1\50\1\47\1\51\4\47\3\6\5\47\4\6"+
    "\1\215\20\6\4\47";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4656];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\45\1\4\0\36\1\1\0\25\1\1\11\40\1"+
    "\1\0\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  int get_line(){	return yyline;}
  int get_column(){	return yycolumn;}

StringBuffer string = new StringBuffer();
  private java_cup.runtime.Symbol symbol(int type) {
    return new java_cup.runtime.Symbol(type, yyline, yycolumn);
  }
  private java_cup.runtime.Symbol symbol(int type, Object value) {
    return new java_cup.runtime.Symbol(type, yyline, yycolumn, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public OberonScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException, LexicalException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return symbol(Symbol.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new IllegalSymbolException();
            }
            // fall through
          case 54: break;
          case 2:
            { 
            }
            // fall through
          case 55: break;
          case 3:
            { return symbol(Symbol.NOTEQUAL);
            }
            // fall through
          case 56: break;
          case 4:
            { if(yylength() > 24) throw new IllegalIdentifierLengthException();
                                        else return  symbol(Symbol.IDENTIFIER,yytext());
            }
            // fall through
          case 57: break;
          case 5:
            { return symbol(Symbol.AND);
            }
            // fall through
          case 58: break;
          case 6:
            { return symbol(Symbol.LeftParenthesis);
            }
            // fall through
          case 59: break;
          case 7:
            { return symbol(Symbol.RightParenthesis);
            }
            // fall through
          case 60: break;
          case 8:
            { return symbol(Symbol.TIMES );
            }
            // fall through
          case 61: break;
          case 9:
            { return symbol(Symbol.PLUS);
            }
            // fall through
          case 62: break;
          case 10:
            { return symbol(Symbol.COMMA);
            }
            // fall through
          case 63: break;
          case 11:
            { return symbol(Symbol.MINUS);
            }
            // fall through
          case 64: break;
          case 12:
            { return symbol(Symbol.POINT);
            }
            // fall through
          case 65: break;
          case 13:
            { if(yylength() > 12) throw new IllegalIntegerRangeException();
                                        else return  symbol(Symbol.IDENTIFIER,yytext());
            }
            // fall through
          case 66: break;
          case 14:
            { return symbol(Symbol.COLON);
            }
            // fall through
          case 67: break;
          case 15:
            { return symbol(Symbol.SEMICOLON);
            }
            // fall through
          case 68: break;
          case 16:
            { return symbol(Symbol.LessThan);
            }
            // fall through
          case 69: break;
          case 17:
            { return symbol(Symbol.EQUAL);
            }
            // fall through
          case 70: break;
          case 18:
            { return symbol(Symbol.GreatThan);
            }
            // fall through
          case 71: break;
          case 19:
            { return symbol(Symbol.LeftBracket);
            }
            // fall through
          case 72: break;
          case 20:
            { return symbol(Symbol.RightBracket);
            }
            // fall through
          case 73: break;
          case 21:
            { return symbol(Symbol.NOT);
            }
            // fall through
          case 74: break;
          case 22:
            { throw new MismatchedCommentException();
            }
            // fall through
          case 75: break;
          case 23:
            { throw new IllegalIntegerException();
            }
            // fall through
          case 76: break;
          case 24:
            { throw new IllegalOctalException();
            }
            // fall through
          case 77: break;
          case 25:
            { return symbol(Symbol.ASSIGNMENT);
            }
            // fall through
          case 78: break;
          case 26:
            { return symbol(Symbol.LessThanOrEqual);
            }
            // fall through
          case 79: break;
          case 27:
            { return symbol(Symbol.GreatThanOrEqual);
            }
            // fall through
          case 80: break;
          case 28:
            { return symbol(Symbol.DO);
            }
            // fall through
          case 81: break;
          case 29:
            { return symbol(Symbol.IF);
            }
            // fall through
          case 82: break;
          case 30:
            { return symbol(Symbol.OF);
            }
            // fall through
          case 83: break;
          case 31:
            { return symbol(Symbol.OR);
            }
            // fall through
          case 84: break;
          case 32:
            { return symbol(Symbol.DIV);
            }
            // fall through
          case 85: break;
          case 33:
            { return symbol(Symbol.END);
            }
            // fall through
          case 86: break;
          case 34:
            { return symbol(Symbol.MOD);
            }
            // fall through
          case 87: break;
          case 35:
            { return symbol(Symbol.VAR);
            }
            // fall through
          case 88: break;
          case 36:
            { return symbol(Symbol.ELSE);
            }
            // fall through
          case 89: break;
          case 37:
            { return symbol(Symbol.READ);
            }
            // fall through
          case 90: break;
          case 38:
            { return symbol(Symbol.THEN);
            }
            // fall through
          case 91: break;
          case 39:
            { return symbol(Symbol.TRUE);
            }
            // fall through
          case 92: break;
          case 40:
            { return symbol(Symbol.TYPE);
            }
            // fall through
          case 93: break;
          case 41:
            { return symbol(Symbol.ARRAY);
            }
            // fall through
          case 94: break;
          case 42:
            { return symbol(Symbol.BEGIN);
            }
            // fall through
          case 95: break;
          case 43:
            { return symbol(Symbol.CONST);
            }
            // fall through
          case 96: break;
          case 44:
            { return symbol(Symbol.ELSIF);
            }
            // fall through
          case 97: break;
          case 45:
            { return symbol(Symbol.FALSE);
            }
            // fall through
          case 98: break;
          case 46:
            { return symbol(Symbol.WHILE);
            }
            // fall through
          case 99: break;
          case 47:
            { return symbol(Symbol.WRITE);
            }
            // fall through
          case 100: break;
          case 48:
            { return symbol(Symbol.MODULE);
            }
            // fall through
          case 101: break;
          case 49:
            { return symbol(Symbol.RECORD);
            }
            // fall through
          case 102: break;
          case 50:
            { return symbol(Symbol.BOOLEAN);
            }
            // fall through
          case 103: break;
          case 51:
            { return symbol(Symbol.INTEGER);
            }
            // fall through
          case 104: break;
          case 52:
            { return symbol(Symbol.WRITELN);
            }
            // fall through
          case 105: break;
          case 53:
            { return symbol(Symbol.PROCEDURE);
            }
            // fall through
          case 106: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
