
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Symbol {
  /* terminals */
  public static final int LeftParenthesis = 40;
  public static final int CONST = 6;
  public static final int ASSIGNMENT = 24;
  public static final int LessThanOrEqual = 27;
  public static final int ELSIF = 16;
  public static final int INTEGER = 18;
  public static final int NOTEQUAL = 25;
  public static final int LeftBracket = 38;
  public static final int ARRAY = 10;
  public static final int MINUS = 31;
  public static final int WRITE = 46;
  public static final int SEMICOLON = 35;
  public static final int NOT = 32;
  public static final int AND = 34;
  public static final int RECORD = 9;
  public static final int RightBracket = 39;
  public static final int TYPE = 7;
  public static final int GreatThan = 28;
  public static final int OR = 22;
  public static final int COMMA = 37;
  public static final int DIV = 20;
  public static final int BEGIN = 4;
  public static final int RightParenthesis = 41;
  public static final int PLUS = 30;
  public static final int WRITELN = 47;
  public static final int IF = 14;
  public static final int OF = 11;
  public static final int EOF = 0;
  public static final int BOOLEAN = 19;
  public static final int EQUAL = 23;
  public static final int TRUE = 43;
  public static final int error = 1;
  public static final int GreatThanOrEqual = 29;
  public static final int NUMBER = 49;
  public static final int MOD = 21;
  public static final int MODULE = 3;
  public static final int TIMES = 33;
  public static final int COLON = 42;
  public static final int ELSE = 17;
  public static final int LessThan = 26;
  public static final int READ = 45;
  public static final int POINT = 36;
  public static final int WHILE = 12;
  public static final int THEN = 15;
  public static final int END = 5;
  public static final int FALSE = 44;
  public static final int VAR = 8;
  public static final int PROCEDURE = 2;
  public static final int DO = 13;
  public static final int IDENTIFIER = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROCEDURE",
  "MODULE",
  "BEGIN",
  "END",
  "CONST",
  "TYPE",
  "VAR",
  "RECORD",
  "ARRAY",
  "OF",
  "WHILE",
  "DO",
  "IF",
  "THEN",
  "ELSIF",
  "ELSE",
  "INTEGER",
  "BOOLEAN",
  "DIV",
  "MOD",
  "OR",
  "EQUAL",
  "ASSIGNMENT",
  "NOTEQUAL",
  "LessThan",
  "LessThanOrEqual",
  "GreatThan",
  "GreatThanOrEqual",
  "PLUS",
  "MINUS",
  "NOT",
  "TIMES",
  "AND",
  "SEMICOLON",
  "POINT",
  "COMMA",
  "LeftBracket",
  "RightBracket",
  "LeftParenthesis",
  "RightParenthesis",
  "COLON",
  "TRUE",
  "FALSE",
  "READ",
  "WRITE",
  "WRITELN",
  "IDENTIFIER",
  "NUMBER"
  };

  /* non terminals */
  static final int procedure_begin = 19;
  static final int const_list = 3;
  static final int module = 15;
  static final int field_list = 25;
  static final int selector = 33;
  static final int format_parameters = 22;
  static final int field_list_list = 27;
  static final int special_type = 30;
  static final int procedure_body = 21;
  static final int term_list = 36;
  static final int module_body = 16;
  static final int readwritestatement = 6;
  static final int array_type = 28;
  static final int if_statement = 12;
  static final int var_declarations = 2;
  static final int type_declarations = 1;
  static final int assignment = 8;
  static final int actual_parameters = 32;
  static final int expression = 31;
  static final int elsif_statement = 13;
  static final int statement = 10;
  static final int record_type = 26;
  static final int term = 35;
  static final int procedure_heading = 20;
  static final int else_statement = 14;
  static final int procedure_declaration = 18;
  static final int fp_section = 23;
  static final int type_list = 4;
  static final int var_list = 5;
  static final int while_statement = 11;
  static final int procedure_call = 7;
  static final int identifier_list = 24;
  static final int simple_expression_list = 38;
  static final int factor = 37;
  static final int declarations = 17;
  static final int expression_list = 29;
  static final int statement_sequence = 9;
  static final int const_declarations = 0;
  static final int simple_expression = 34;
}

